stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: yarn test

build:
  stage: build
  script: yarn build --branch master

deploy_production:
  stage: deploy
  tags:
    - ansible
  script:
    - ansible-playbook -i staging ansible/deploy.yml
  environment:
    name: production
    url: http://temporal.dk
  only:
  - master
