---
- hosts: localhost
  tasks:
    - name: build
      shell: yarn build 

- hosts: webserver
  tasks:
  - name: Copy build to webservers
    synchronize:
      src: ../dist/
      dest: ~/srv/temporal
      delete: true