# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile --dev
    - run: yarn build
    - run: yarn test
      env:
        CI: true

    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      env:
        HOST: khophi.com
        USERNAME: khophi
        PORT: 22
        KEY: ${{ secrets.forSSH }}
      with:
        source: "./dist/your-angular-app-name/"
        target: "/home/user/domain.com/pwa/"
        strip_components: 3 # this is important
   

  
